// @ts-check
import { faker } from '@faker-js/faker/locale/en';
import fs from 'node:fs';
import path from 'node:path';
import { format } from 'prettier';
import prettierConfig from '../.prettierrc.json' with { type: 'json' };

const rootDir = path.resolve(import.meta.dirname, '..');
const srcDir = path.resolve(rootDir, 'src');

/**
 * @type {{ [ModuleName in keyof import('@faker-js/faker').Faker]?: (keyof import('@faker-js/faker').Faker[ModuleName] | '*')[]; } & { _randomizer: ['*'] }}
 */
const invalidEntrypoints = {
  // internal fields - does not exist in type but during runtime
  _randomizer: ['*'],
  // definitions - doesn't really do anything
  rawDefinitions: ['*'],
  definitions: ['*'],
  // methods require arguments - this is not possible for now
  date: ['between', 'betweens'],
  helpers: ['*'],
  string: ['fromCharacters'],
  // deprecated
  image: ['urlLoremFlickr'],
};

/**
 * @param {string} moduleName
 * @returns {boolean}
 */
function isValidModule(moduleName) {
  // @ts-expect-error Figure out how to define type in js file to satisfy TS language service
  const invalidModuleRef = invalidEntrypoints[moduleName];
  if (invalidModuleRef === undefined) {
    return true;
  }

  if (invalidModuleRef.includes('*')) {
    return false;
  }

  return true;
}

/**
 * @param {string} moduleName
 * @param {string} entryName
 * @returns {boolean}
 */
function isValidEntry(moduleName, entryName) {
  // @ts-expect-error Figure out how to define type in js file to satisfy TS language service
  const invalidModuleRef = invalidEntrypoints[moduleName];
  if (invalidModuleRef === undefined) {
    return true;
  }

  if (invalidModuleRef.includes('*')) {
    return false;
  }

  if (invalidModuleRef.includes(entryName)) {
    return false;
  }

  return true;
}

async function generateApi() {
  let apiObjectString = '{';
  const moduleEntries = Object.entries(faker);
  for (const [moduleName, moduleRef] of moduleEntries) {
    const isObject = typeof moduleRef === 'object' && moduleRef !== null;
    if (!isObject) {
      continue;
    }

    if (!isValidModule(moduleName)) {
      continue;
    }

    let moduleObjectString = '{';
    const allEntryEntries = Object.entries(moduleRef);
    for (const [entryName, entryRef] of allEntryEntries) {
      if (typeof entryRef !== 'function') {
        continue;
      }

      if (!isValidEntry(moduleName, entryName)) {
        continue;
      }

      moduleObjectString += `${entryName}: () => faker.${moduleName}.${entryName}(),`;
    }

    moduleObjectString += '}';

    apiObjectString += `${moduleName}: ${moduleObjectString},`;
  }

  apiObjectString += '}';

  const apiFilePath = path.resolve(srcDir, 'api.ts');
  const apiFileContent = await format(
    `
    /*
     * This file is automatically generated.
     * Run 'npm run generate:api' to update.
     */

    import { faker } from '@faker-js/faker/locale/en';
      
    export const API = ${apiObjectString} satisfies Record<string, Record<string, () => unknown>>;
    `,
    // @ts-expect-error migrate to prettier js|ts config file to get type definitions correctly
    { ...prettierConfig, parser: 'typescript' },
  );
  fs.writeFileSync(apiFilePath, apiFileContent);
}

await generateApi();
